-- INT; DECIMAL(M,N); VARCHAR(M), 
-- BLOB, DATE "YYYY-MM-DD", TIMESTAMP "YYYY-MM-DD HH:MM:SS"
-- PRIMARY KEY, AUTO_INCREMENT, NOT NULL, DEFAULT value, UNIQUE, FOREIGN KEY, REFERENCES, ON DELETE, SET NULL, SET CASCADE
CREATE TABLE orders (
	order_id INT PRIMARY KEY AUTO_INCREMENT,
    product VARCHAR(50) NOT NULL,
    price DECIMAL(5,2) NOT NULL,
    customer_id INT,
    FOREIGN KEY(customer_id) REFERENCES customers(customer_id) ON DELETE SET NULL
)